### ISSUE TITLE
Button active css does not work

### ISSUE THREAD

**Issue by IvyWang-SH** [pixilab/blocks-css#1]
Hello,

I add button css and its active state with following code. However the button active css doesn't work. Could you help me out with this issue? Thanks
`.Button-ctl.equipment>div {
	background-color: #696969;
	background-image: url('homePage-btn-equipment.png');
	width: 172px;
	height: 40px;
	border-radius: 2px;
}

.Button-ctl.equipment.active>div {
	background-color: #EBB626;
}`

BTW, the border-radius also doesn't work.

**Comment by TheWizz** [comment]
Would you mind posting this question on our user forum instead,  and we'll help you there:

	https://pixilab.se/forum

Thanks!

Mike

**Comment by TheWizz** [comment]
You may also want to check out this article on our Wiki:

https://pixilab.se/docs/blocks/custom_styling

I believe the class you're looking for there is _pressed_, which indicates that the button is currently being held down using touch or mouse. If you have any follow-up questions, please post on our forum.

Mike
